services:
  db:
    container_name: postgrescontainer
    image: postgres:16.1
    restart: always
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}

    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
       - postgresvolume:/var/lib/postgresql/data
       - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql

  pgadmin:
    container_name: pgadmincontainer
    image: 'dpage/pgadmin4:8.5'
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
       PGADMIN_DEFAULT_ADDRESS: 5050
       PGADMIN_LISTENER_PORT: 5050
    expose:
      - 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadminvolume:/var/lib/pgadmin


volumes:
  pgadminvolume:
  postgresvolume:


