#Database

POSTRESQL_USERNAME: user
POSTRESQL_PASSWORD: sefyu8919
POSTRESQL_HOST: localhost
POSTRESQL_PORT: 5432
POSTRESQL_DATABASE: securedocdb

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

# Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085